MACRO(DETECT_COMPILER)
IF(NOT CMAKE_COMPILER_IS_GNUCC)
  CHECK_C_SOURCE_COMPILES(
"#ifndef __INTEL_COMPILER
#error no icc
#endif
int main(){}
" CMAKE_COMPILER_IS_ICC)
ENDIF(NOT CMAKE_COMPILER_IS_GNUCC)
ENDMACRO(DETECT_COMPILER)

MACRO(MACRO_TEST ARG VAR)
CHECK_C_SOURCE_COMPILES(
"#ifndef ${ARG}
#error ${ARG} macro not defined
#endif
int main(){}
" ${VAR})
ENDMACRO(MACRO_TEST)

# Check pointer width independently of compiler brand.  The old GNU-only
# __LP64__ probe skipped Clang/Apple Clang, which is the primary compiler for
# AArch64 and arm64e Darwin builds.
MACRO(CHECK_64BITS)
IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
  SET(HAVE_64BITS TRUE)
ELSE(CMAKE_SIZEOF_VOID_P EQUAL 8)
  SET(HAVE_64BITS FALSE)
ENDIF(CMAKE_SIZEOF_VOID_P EQUAL 8)

IF(HAVE_64BITS AND CMAKE_SYSTEM_MACHINE MATCHES "i.86")
  SET(CMAKE_SYSTEM_MACHINE "x86_64")
ENDIF(HAVE_64BITS AND CMAKE_SYSTEM_MACHINE MATCHES "i.86")

IF(NOT HAVE_64BITS AND CMAKE_SYSTEM_MACHINE MATCHES "x86_64")
  SET(CMAKE_SYSTEM_MACHINE "i686")
ENDIF(NOT HAVE_64BITS AND CMAKE_SYSTEM_MACHINE MATCHES "x86_64")
ENDMACRO(CHECK_64BITS)
